import scoreMatrix
import time

# Test Cases - can be modified to be read from text file (file = open("filePath", "r"); file.read())

# Test Case 1
seq1 = "ATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCAT"
seq2 = "TTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAA"

# Test Case 2
# seq1 = "ATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCAT"
# seq2 = "TTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAA"

# Test Case 3
# seq1 = "ATAGACGACATGGGGACAGCATATAGACGACATGGGGACAGCAT"
# seq2 = "TTTAGCATGCGCATATCAGCAATTTAGCATGCGCATATCAGCAA"

# Test Case 4
# seq1 = "ATAGACGACATGGGGACAGCAT"
# seq2 = "TTTAGCATGCGCATATCAGCAA"

# Test Case 5
# seq1 = "ATAGACGACAT"
# seq2 = "TTTAGCATGCG"

# Test Case 6
# seq1 = "ATAGA"
# seq2 = "TTTAG"

match = 2
mismatch = -1
maxScore = 0
maxPosition = (0, 0)
rowcounter = 0
colcounter = 0
rows = len(seq1)
cols = len(seq2)
max_d_count = 0
score_matrix = scoreMatrix.create(seq1, seq2);
score_index_list = []
threads = []